version: '3.8'

services:
  app:
    build: .
    container_name: consulta-cep-app
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/consulta_cep_db
      SPRING_DATASOURCE_USERNAME: consulta_user
      SPRING_DATASOURCE_PASSWORD: consulta_pass
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
    restart: unless-stopped

  postgres:
    image: postgres:16-alpine
    container_name: consulta-cep-postgres
    environment:
      POSTGRES_DB: consulta_cep_db
      POSTGRES_USER: consulta_user
      POSTGRES_PASSWORD: consulta_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U consulta_user -d consulta_cep_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: consulta-cep-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
