spring.application.name=consultaCepCorreios

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/consulta_cep_db
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=consulta_user
spring.datasource.password=consulta_pass
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Logging Configuration
logging.level.root=INFO
logging.level.com.dersolopes.consultaCepCorreios=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
logging.file.name=logs/consulta-cep-correios.log
logging.file.max-size=10MB
logging.file.max-history=30
